# https://docs.docker.com/compose/rails/

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev

    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - RAILS_ENV=development

    ports:
      - 3000:3000

    stdin_open: true

    tty: true

    env_file:
      - development.env

    entrypoint: ./dev-docker-entrypoint.sh

    volumes:
      - .:/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.4-alpine

    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    ports:
      - 5432:5432

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: {}
  gem_cache: {}
  shared_data: {}
