services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev

    command: ['bin/rails', 'server', '-p', '3000', '-b', '0.0.0.0']

    entrypoint: ./dev.entrypoint.sh

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - RAILS_ENV=development

    ports:
      - 3000:3000

    stdin_open: true

    tty: true

    volumes:
      - .:/home/darnoc/app
      - shared-data:/var/shared
      - gem-cache:/usr/local/bundle/gems

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.3-bullseye

    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    ports:
      - 5432:5432

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: {}
  gem-cache: {}
  shared-data: {}
