# https://docs.docker.com/compose/rails/

version: '2.4'

services:
  traefik:
    image: traefik:1.7-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:80'
    command:
      - --docker
      - --docker.domain=traefik
      - --docker.watch
      - --api
      - --defaultentrypoints=http,https
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.localhost
    networks:
      - frontend
      - backend

  web:
    build:
      context: .
      target: dev

    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails s -b '0.0.0.0'"

    environment:
      - RAILS_ENV=development

    networks:
      - frontend

    volumes:
      - .:/app

    labels:
      - traefik.port=80
      - traefik.frontend.rule=Host:web.localhost

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.0
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password
    networks:
      - backend
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1

networks:
  frontend:
  backend:

volumes:
  db-data:
